[workspace]
resolver = "2"
members=[
    "crates/parser", "crates/vm",
]

[workspace.package]
name="wasmpy"
edition="2024"
license="Apache-2.0"
version="0.1.0"

[workspace.dependencies]
anyhow = "1.0"
logos="0.16.1"
