[package]
name = "wasm"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
parser = { path = "../parser" }
ast = { path = "../ast" }
wasm-encoder = "0.245.1"
thiserror = "2"
logos.workspace = true

[dev-dependencies]
wasmparser = "0.245.1"
